name: cygne
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - pandas
  - pip
  - openpyxl
  - six
  - pillow
  - sqlalchemy
  - scipy
  - psycopg2
  - pymssql
  - xlrd
  - geopy
  - pyodbc
  - geopandas=0.14
  - momepy=0.7
  - numpy=1.26.4
  - folium
  - requests
  - ipython
  - deprecated
  - osmnx
  - ipykernel
  - pyarrow
  - geoalchemy2